sudo: false
language: ruby
cache: bundler
before_install:
  - export TZ=America/New_York
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database research-master-id_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
